### ISSUE TITLE
temp c to voltage

### ISSUE THREAD

**Issue by teacdance** [zagor/fineoffset#1]
Hi

can somehow to change °C to V (voltage )

**Comment by zagor** [comment]
Sure! The protocol doesn't specify a unit for the value, so you can send whatever data you want.

**Comment by teacdance** [comment]
But can change that c letter to v.. c letter come telldus i think it cannot change...  otherwise it works really well..

**Comment by zagor** [comment]
The letter C is not part of the protocol.
